version: "3"
services:
  app:
    image: fitup-api.dev:latest
    volumes:
      - "./:/go/src/fitup-api/"
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mongo:4.0.4-xenial
    ports:
      - "27018:27017"
    volumes:
      - fitup-api:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
volumes:
  fitup-api:
