version: "3"
services:
  app:
    image: fitup-api.dev:latest
    volumes:
      - "./:/go/src/github.com/fitup/api"
    ports:
      - "5001:5000"
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - fitup-api-pg:/data/db
    environment:
      POSTGRES_USER: fitup
      POSTGRES_PASSWORD: fitup
volumes:
  fitup-api-pg:
