FROM golang:1.12.1-alpine3.9
RUN apk update && apk add git
COPY . /go/src/github.com/fitup/api
WORKDIR /go/src/github.com/fitup/api
RUN go get ./
CMD go get github.com/githubnemo/CompileDaemon && CompileDaemon -command="./api"
EXPOSE 5000
