FROM golang:alpine
RUN apk update && apk add git
COPY . /go/src/github.com/fitup/api
WORKDIR /go/src/github.com/fitup/api
RUN GO111MODULE=on go get ./
CMD go get github.com/githubnemo/CompileDaemon && CompileDaemon -command="./api"
EXPOSE 5000
